from docx import Document
from docx.shared import Inches

document = Document()
# picture
document.add_picture('tupix.jpg', width=Inches(1.2))

name = input('What is your name ? ')
phone_number = input('What is your phone number ? ')
email_address = input('What is your email ? ')

document.add_paragraph(
    name + '|' + phone_number + '|' + email_address
)

document.add_heading('About')
document.add_paragraph(
    input('write about yourself')
)

# Education
document.add_heading('Education')
p = document.add_paragraph()

education = input('Name of institution ?')
start_date = input('start date')
end_date = input('End date')
studied = input('what did you study in ' + education)

p.add_run(education + ':' + ' ').bold =True
p.add_run(' ' + start_date + '-' + end_date + '\n' + studied).italic

#more education
while True:
    has_more_education = input('Do you want to add more schools ? Yes or No')
    if has_more_education.lower() == 'yes':

        p = document.add_paragraph()
        education = input('Name of institution ?')
        start_date = input('start date')
        end_date = input('End date')
        studied = input('what did you study in ' + education)

        p.add_run(education + ':' + ' ').bold =True
        p.add_run(' ' + start_date + '-' + end_date + '\n' + studied).italic
    else:
        break
# work experience
document.add_heading('Experience')
p = document.add_paragraph()
employer = input('who was your employer ?')
from_date = input('start date?')
to_date = input('end date ?')
position = input('what was your role in' + employer + '?')
location = input('job location ?')

p.add_run(employer + ':' + ' ').bold =True
p.add_run(' ' + from_date + '-' + to_date + '\n' + position + ' ' + ' ' + location )

#more work experience
while True:
    has_more_experience = input('Do you have more work experience ? Yes or No')
    if has_more_experience.lower() == 'yes':
        p = document.add_paragraph()
        employer = input('who was your employer ?')
        from_date = input('start date?')
        to_date = input('end date ?')
        position = input('what was your role in' + employer + '?')
        location = input('job location ?')

        p.add_run(employer + ':' + ' ').bold =True
        p.add_run(' ' + from_date + '-' + to_date + '\n' + position + ' ' + ' ' + location )
    else:
        break
#skills
document.add_heading('Skills')
skills = input('what type of skill do you have ?')
p = document.add_paragraph(skills)
p.style = 'List Bullet'

# more skills
while True:
    has_more_skills = input('Do you have more skills ? Yes or No')
    if has_more_skills.lower() == 'yes':
        skills = input('what type of skill do you have ?')
        p = document.add_paragraph(skills)
        p.style = 'List Bullet'
    else:
        break

#footer
section = document.sections[0]
footer = section.footer
p = footer.paragraphs[0]
p.text = 'Cv generated by Jamiu as a project'




document.save('cv.docx')